import type { AnimationPreset } from '../types';

export const ANIMATION_PRESETS: AnimationPreset[] = [
  // Locomotion
  {
    id: 'walk-cycle',
    name: 'Walk Cycle',
    icon: '🚶',
    description: 'Klasyczny cykl chodu - 8 klatek, pełna pętla',
    category: 'locomotion',
    frameCount: 8,
    fps: 12,
  },
  {
    id: 'run-cycle',
    name: 'Run Cycle',
    icon: '🏃',
    description: 'Dynamiczny bieg z fazą lotu - 6 klatek',
    category: 'locomotion',
    frameCount: 6,
    fps: 16,
  },
  {
    id: 'jump',
    name: 'Jump',
    icon: '⬆️',
    description: 'Skok: przygotowanie, faza lotu, lądowanie - 7 klatek',
    category: 'locomotion',
    frameCount: 7,
    fps: 12,
  },
  {
    id: 'dash',
    name: 'Dash / Sprint',
    icon: '💨',
    description: 'Szybki zryw / dash - 4 klatki',
    category: 'locomotion',
    frameCount: 4,
    fps: 20,
  },
  {
    id: 'climb',
    name: 'Climb',
    icon: '🧗',
    description: 'Wspinaczka po drabinie/ścianie - 6 klatek',
    category: 'locomotion',
    frameCount: 6,
    fps: 10,
  },

  // Action
  {
    id: 'attack-melee',
    name: 'Melee Attack',
    icon: '⚔️',
    description: 'Atak mieczem / bronią białą - 6 klatek',
    category: 'action',
    frameCount: 6,
    fps: 16,
  },
  {
    id: 'attack-ranged',
    name: 'Ranged Attack',
    icon: '🏹',
    description: 'Strzał / rzut - 5 klatek',
    category: 'action',
    frameCount: 5,
    fps: 14,
  },
  {
    id: 'cast-spell',
    name: 'Cast Spell',
    icon: '✨',
    description: 'Rzucanie zaklęcia - 8 klatek',
    category: 'action',
    frameCount: 8,
    fps: 12,
  },
  {
    id: 'take-damage',
    name: 'Take Damage',
    icon: '💥',
    description: 'Otrzymanie obrażeń / flinch - 4 klatki',
    category: 'action',
    frameCount: 4,
    fps: 12,
  },
  {
    id: 'death',
    name: 'Death',
    icon: '☠️',
    description: 'Animacja śmierci - 8 klatek',
    category: 'action',
    frameCount: 8,
    fps: 10,
  },

  // Idle
  {
    id: 'idle-breathe',
    name: 'Idle (Breathing)',
    icon: '😌',
    description: 'Subtelne oddychanie - 4 klatki',
    category: 'idle',
    frameCount: 4,
    fps: 6,
  },
  {
    id: 'idle-blink',
    name: 'Idle (Blink)',
    icon: '😉',
    description: 'Postać z mruganiem oczu - 8 klatek',
    category: 'idle',
    frameCount: 8,
    fps: 4,
  },
  {
    id: 'idle-combat',
    name: 'Combat Stance',
    icon: '🥊',
    description: 'Gotowość do walki - 4 klatki',
    category: 'idle',
    frameCount: 4,
    fps: 8,
  },

  // Effects
  {
    id: 'explosion',
    name: 'Explosion',
    icon: '💥',
    description: 'Efekt eksplozji - 6 klatek',
    category: 'effect',
    frameCount: 6,
    fps: 16,
  },
  {
    id: 'dust-cloud',
    name: 'Dust Cloud',
    icon: '💨',
    description: 'Chmura kurzu (bieg/lądowanie) - 5 klatek',
    category: 'effect',
    frameCount: 5,
    fps: 14,
  },
  {
    id: 'sparkle',
    name: 'Sparkle / Shine',
    icon: '✨',
    description: 'Efekt błysku - 4 klatki',
    category: 'effect',
    frameCount: 4,
    fps: 12,
  },
];

export const PRESET_CATEGORIES = [
  { id: 'locomotion', name: 'Ruch', icon: '🚶' },
  { id: 'action', name: 'Akcja', icon: '⚔️' },
  { id: 'idle', name: 'Bezczynność', icon: '😌' },
  { id: 'effect', name: 'Efekty', icon: '✨' },
] as const;
